name: epub_parser
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/ngocmanh1609/epub_parser
issue_tracker: https://github.com/ngocmanh1609/epub_parser
version: 3.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  archive: ^3.3.7
  quiver: ^3.0.1+1
  xml: ^6.1.0
  image: ^4.0.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.7
  path: ^1.8.0
  pedantic: ^1.11.0
